In [110]:
import pandas as pd
import numpy as np

In [111]:
df_sulak_alan = pd.read_csv('../data/sulak_alan.csv', delimiter=';')
df_sulak_alan.dropna(inplace=True)
df_sulak_alan

    ilce_adi mahalle_adi sulak_alan_miktari
0     Ahırlı    ALİÇERÇİ                10%
1     Ahırlı     BADEMLİ                10%
2     Ahırlı   BALIKLAVA                20%
3     Ahırlı     BÜYÜKÖZ                 5%
4     Ahırlı     ÇİFTLİK                75%
..       ...         ...                ...
767    Yunak     YAVAŞLI                50%
768    Yunak    YEŞİLOBA                50%
769    Yunak  YEŞİLYAYLA                10%
770    Yunak       YIĞAR                30%
771    Yunak       SARAY                60%

[772 rows x 3 columns]

In [112]:
df_en_cok_yetistirilen = pd.read_csv('../data/en_cok_yetistirilen.csv', delimiter=';')
df_en_cok_yetistirilen.dropna(inplace=True)
df_en_cok_yetistirilen

    ilce_adi mahalle_adi                   en_cok_yetistirilen_urunler
0     Ahırlı    ALİÇERÇİ        BUĞDAY, ARPA, MERCİMEK, NOHUT, FASULYE
1     Ahırlı     BADEMLİ                     BUĞDAY, ARPA, NOHUT, ERİK
2     Ahırlı   BALIKLAVA                    BUĞDAY, ELMA, ÇİLEK, NOHUT
3     Ahırlı     BÜYÜKÖZ                                  BUĞDAY, ARPA
4     Ahırlı     ÇİFTLİK                         BUĞDAY, ARPA, FASULYE
..       ...         ...                                           ...
767    Yunak     YAVAŞLI  MISIR, BUĞDAY, ARPA, AYÇİÇEĞİ, ŞEKER PANCARI
768    Yunak    YEŞİLOBA   MISIR, BUĞDAY, ARPA, ŞEKER PANCARI, FASULYE
769    Yunak  YEŞİLYAYLA                         BUĞDAY, ARPA, FASULYE
770    Yunak       YIĞAR                 MISIR, BUĞDAY, ARPA, AYÇİÇEĞİ
771    Yunak       SARAY                       MISIR, BUĞDAY, AYÇİÇEĞİ

[771 rows x 3 columns]

In [113]:
df_sulama_kaynagi_tipi = pd.read_csv('../data/sulama_kaynagi_tipi.csv', delimiter=';')
df_sulama_kaynagi_tipi.dropna(inplace=True)
df_sulama_kaynagi_tipi

    ilce_adi mahalle_adi sulama_suyu_kaynagi_yonetimi
0     Ahırlı    ALİÇERÇİ                          YOK
1     Ahırlı     BADEMLİ                          YOK
2     Ahırlı   BALIKLAVA               SULAMA BİRLİĞİ
3     Ahırlı     BÜYÜKÖZ                ŞAHSİ KUYULAR
4     Ahırlı     ÇİFTLİK                ŞAHSİ KUYULAR
..       ...         ...                          ...
767    Yunak     YAVAŞLI                ŞAHSİ KUYULAR
768    Yunak    YEŞİLOBA                ŞAHSİ KUYULAR
769    Yunak  YEŞİLYAYLA                ŞAHSİ KUYULAR
770    Yunak       YIĞAR                ŞAHSİ KUYULAR
771    Yunak       SARAY                ŞAHSİ KUYULAR

[770 rows x 3 columns]

In [114]:
df_sulanabilir_alanda_yetistirilen = pd.read_csv('../data/sulanabilir_alanda_yetistirilen.csv', delimiter=';')
df_sulanabilir_alanda_yetistirilen.dropna(inplace=True)
df_sulanabilir_alanda_yetistirilen

    ilce_adi mahalle_adi        sulanabilir_alanda_yetistirilen_urunler
0     Ahırlı    ALİÇERÇİ                                            YOK
1     Ahırlı     BADEMLİ                                            YOK
2     Ahırlı   BALIKLAVA                ELMA, KİRAZ, VİŞNE, ÇİLEK, ERİK
3     Ahırlı     BÜYÜKÖZ                                   BUĞDAY, ARPA
4     Ahırlı     ÇİFTLİK                                        FASULYE
..       ...         ...                                            ...
767    Yunak     YAVAŞLI                 ŞEKER PANCARI, MISIR, AYÇİÇEĞİ
768    Yunak    YEŞİLOBA         ŞEKER PANCARI, MISIR, FASULYE, DOMATES
769    Yunak  YEŞİLYAYLA                                        FASULYE
770    Yunak       YIĞAR                                MISIR, AYÇİÇEĞİ
771    Yunak       SARAY  ŞEKER PANCARI, MISIR, DOMATES, BİBER, PATATES

[770 rows x 3 columns]

In [115]:
df_tarimsal_egitim = pd.read_csv('../data/tarimsal_egitim.csv', delimiter=';')
df_tarimsal_egitim.dropna(inplace=True)
df_tarimsal_egitim

    ilce_adi mahalle_adi                    talep_edilen_tarimsal_egitimler
0     Ahırlı    ALİÇERÇİ  HAYVANCILIK, MODERN BAĞCILIK, TARLA BİTKİLERİ ...
1     Ahırlı     BADEMLİ  MODERN SULAMA SİSTEMLERİ, SEBZE YETİŞTİRİCİLİĞ...
2     Ahırlı   BALIKLAVA  MODERN SULAMA SİSTEMLERİ, SEBZE YETİŞTİRİCİLİĞ...
3     Ahırlı     BÜYÜKÖZ  MODERN BAĞCILIK, ARI YETİŞTİRİCİLİĞİ, TARLA Bİ...
4     Ahırlı     ÇİFTLİK                                        HAYVANCILIK
..       ...         ...                                                ...
767    Yunak     YAVAŞLI                    TARLA BİTKİLERİ YETİŞTİRİCİLİĞİ
768    Yunak    YEŞİLOBA  MODERN SULAMA SİSTEMLERİ, MODERN MEYVECİLİK, H...
769    Yunak  YEŞİLYAYLA  MODERN SULAMA SİSTEMLERİ, HAYVANCILIK, TIBBİ V...
770    Yunak       YIĞAR  MODERN MEYVECİLİK, HAYVANCILIK, TARLA BİTKİLER...
771    Yunak       SARAY  ARI YETİŞTİRİCİLİĞİ, BİOTEKNİK MÜCADELE VE İYİ...

[770 rows x 3 columns]

In [116]:
df_tarimsal_sulama_durum_bilgisi = pd.read_csv('../data/tarimsal_sulama_durum_bilgisi.csv', delimiter=';')
df_tarimsal_sulama_durum_bilgisi.dropna(inplace=True)

In [117]:
df_tarimsal_sulama_kaynagi = pd.read_csv('../data/tarimsal_sulama_kaynagi.csv', delimiter=';')
df_tarimsal_sulama_kaynagi.dropna(inplace=True)
df_tarimsal_sulama_kaynagi

    ilce_adi mahalle_adi   tarimsal_sulama_suyu_kaynagi
0     Ahırlı    ALİÇERÇİ                            YOK
1     Ahırlı     BADEMLİ                            YOK
2     Ahırlı   BALIKLAVA                            GÖL
3     Ahırlı     BÜYÜKÖZ                  ŞAHSİ KUYULAR
4     Ahırlı     ÇİFTLİK                            YOK
..       ...         ...                            ...
767    Yunak     YAVAŞLI                  ŞAHSİ KUYULAR
768    Yunak    YEŞİLOBA                  ŞAHSİ KUYULAR
769    Yunak  YEŞİLYAYLA                 YERALTI SULARI
770    Yunak       YIĞAR  ŞAHSİ KUYULAR, YERALTI SULARI
771    Yunak       SARAY  ŞAHSİ KUYULAR, YERALTI SULARI

[770 rows x 3 columns]

In [118]:

merged_df = pd.merge(df_tarimsal_sulama_durum_bilgisi, df_sulama_kaynagi_tipi, on=['ilce_adi', 'mahalle_adi'])
merged_df = pd.merge(merged_df, df_en_cok_yetistirilen, on=['ilce_adi', 'mahalle_adi'])
merged_df = pd.merge(merged_df, df_sulanabilir_alanda_yetistirilen, on=['ilce_adi', 'mahalle_adi'])
merged_df = pd.merge(merged_df, df_tarimsal_egitim, on=['ilce_adi', 'mahalle_adi'])
merged_df = pd.merge(merged_df, df_sulak_alan, on=['ilce_adi', 'mahalle_adi'])
merged_df = pd.merge(merged_df, df_tarimsal_sulama_kaynagi, on=['ilce_adi', 'mahalle_adi'])

merged_df

,ilce_adi,mahalle_adi,tarimsal_sulama_suyu,sulama_suyu_kaynagi_yonetimi,en_cok_yetistirilen_urunler,sulanabilir_alanda_yetistirilen_urunler,talep_edilen_tarimsal_egitimler,sulak_alan_miktari,tarimsal_sulama_suyu_kaynagi
0,Ahırlı,ALİÇERÇİ,YOK,YOK,"BUĞDAY, ARPA, MERCİMEK, NOHUT, FASULYE",YOK,"HAYVANCILIK, MODERN BAĞCILIK, TARLA BİTKİLERİ ...",10%,YOK
1,Ahırlı,BADEMLİ,YOK,YOK,"BUĞDAY, ARPA, NOHUT, ERİK",YOK,"MODERN SULAMA SİSTEMLERİ, SEBZE YETİŞTİRİCİLİĞ...",10%,YOK
2,Ahırlı,BALIKLAVA,VAR,SULAMA BİRLİĞİ,"BUĞDAY, ELMA, ÇİLEK, NOHUT","ELMA, KİRAZ, VİŞNE, ÇİLEK, ERİK","MODERN SULAMA SİSTEMLERİ, SEBZE YETİŞTİRİCİLİĞ...",20%,GÖL
3,Ahırlı,BÜYÜKÖZ,VAR,ŞAHSİ KUYULAR,"BUĞDAY, ARPA","BUĞDAY, ARPA","MODERN BAĞCILIK, ARI YETİŞTİRİCİLİĞİ, TARLA Bİ...",5%,ŞAHSİ KUYULAR
4,Ahırlı,ÇİFTLİK,VAR,ŞAHSİ KUYULAR,"BUĞDAY, ARPA, FASULYE",FASULYE,HAYVANCILIK,75%,YOK
...,...,...,...,...,...,...,...,...,...
764,Yunak,YAVAŞLI,VAR,ŞAHSİ KUYULAR,"MISIR, BUĞDAY, ARPA, AYÇİÇEĞİ, ŞEKER PANCARI","ŞEKER PANCARI, MISIR, AYÇİÇEĞİ",TARLA BİTKİLERİ YETİŞTİRİCİLİĞİ,50%,ŞAHSİ KUYULAR
765,Yunak,YEŞİLOBA,VAR,ŞAHSİ KUYULAR,"MISIR, BUĞDAY, ARPA, ŞEKER PANCARI, FASULYE","ŞEKER PANCARI, MISIR, FASULYE, DOMATES","MODERN SULAMA SİSTEMLERİ, MODERN MEYVECİLİK, H...",50%,ŞAHSİ KUYULAR
766,Yunak,YEŞİLYAYLA,VAR,ŞAHSİ KUYULAR,"BUĞDAY, ARPA, FASULYE",FASULYE,"MODERN SULAMA SİSTEMLERİ, HAYVANCILIK, TIBBİ V...",10%,YERALTI SULARI
767,Yunak,YIĞAR,VAR,ŞAHSİ KUYULAR,"MISIR, BUĞDAY, ARPA, AYÇİÇEĞİ","MISIR, AYÇİÇEĞİ","MODERN MEYVECİLİK, HAYVANCILIK, TARLA BİTKİLER...",30%,"ŞAHSİ KUYULAR, YERALTI SULARI"
768,Yunak,SARAY,VAR,ŞAHSİ KUYULAR,"MISIR, BUĞDAY, AYÇİÇEĞİ","ŞEKER PANCARI, MISIR, DOMATES, BİBER, PATATES","ARI YETİŞTİRİCİLİĞİ, BİOTEKNİK MÜCADELE VE İYİ...",60%,"ŞAHSİ KUYULAR, YERALTI SULARI"

In [120]:
df_sulanabilir_alanda_yetistirilen['ilce_adi'].unique()

array(['Ahırlı', 'Akören', 'Akşehir', 'Altınekin', 'Beyşehir', 'Bozkır',
       'Çeltik', 'Cihanbeyli', 'Çumra', 'Derbent', 'Derebucak',
       'Doğanhisar', 'Emirgazi', 'Ereğli', 'Güneysınır', 'Hadim',
       'Halkapınar', 'Hüyük', 'Ilgın', 'Kadınhanı', 'Karapınar',
       'Karatay', 'Kulu', 'Meram', 'Sarayönü', 'Selçuklu', 'Seydişehir',
       'Taşkent', 'Tuzlukçu', 'Yalıhüyük', 'Yunak'], dtype=object)

In [121]:
df_toprak_ilce = pd.DataFrame([
    {"ilce_adi": "Ahırlı", "toprak_tipi": "Killi toprak"},
    {"ilce_adi": "Akören", "toprak_tipi": "Kumlu toprak"},
    {"ilce_adi": "Akşehir", "toprak_tipi": "Verimli toprak"},
    {"ilce_adi": "Altınekin", "toprak_tipi": "Kumlu toprak"},
    {"ilce_adi": "Beyşehir", "toprak_tipi": "Taşlık toprak"},
    {"ilce_adi": "Bozkır", "toprak_tipi": "Verimli toprak"},
    {"ilce_adi": "Çeltik", "toprak_tipi": "Tuzlu toprak"},
    {"ilce_adi": "Cihanbeyli", "toprak_tipi": "Sulu toprak"},
    {"ilce_adi": "Çumra", "toprak_tipi": "Kumlu-killi toprak"},
    {"ilce_adi": "Derbent", "toprak_tipi": "Killi toprak"},
    {"ilce_adi": "Derebucak", "toprak_tipi": "Kumlu toprak"},
    {"ilce_adi": "Doğanhisar", "toprak_tipi": "Verimli toprak"},
    {"ilce_adi": "Emirgazi", "toprak_tipi": "Taşlık toprak"},
    {"ilce_adi": "Ereğli", "toprak_tipi": "Killi toprak"},
    {"ilce_adi": "Güneysınır", "toprak_tipi": "Verimli toprak"},
    {"ilce_adi": "Hadim", "toprak_tipi": "Kumlu toprak"},
    {"ilce_adi": "Halkapınar", "toprak_tipi": "Taşlık toprak"},
    {"ilce_adi": "Hüyük", "toprak_tipi": "Kumlu-killi toprak"},
    {"ilce_adi": "Ilgın", "toprak_tipi": "Killi toprak"},
    {"ilce_adi": "Kadınhanı", "toprak_tipi": "Verimli toprak"},
    {"ilce_adi": "Karapınar", "toprak_tipi": "Tuzlu toprak"},
    {"ilce_adi": "Karatay", "toprak_tipi": "Killi toprak"},
    {"ilce_adi": "Kulu", "toprak_tipi": "Kumlu toprak"},
    {"ilce_adi": "Meram", "toprak_tipi": "Verimli toprak"},
    {"ilce_adi": "Sarayönü", "toprak_tipi": "Kumlu-killi toprak"},
    {"ilce_adi": "Selçuklu", "toprak_tipi": "Killi toprak"},
    {"ilce_adi": "Seydişehir", "toprak_tipi": "Kumlu toprak"},
    {"ilce_adi": "Taşkent", "toprak_tipi": "Verimli toprak"},
    {"ilce_adi": "Tuzlukçu", "toprak_tipi": "Taşlık toprak"},
    {"ilce_adi": "Yalıhüyük", "toprak_tipi": "Killi toprak"},
    {"ilce_adi": "Yunak", "toprak_tipi": "Kumlu toprak"}
]
)
df_toprak_ilce

      ilce_adi         toprak_tipi
0       Ahırlı        Killi toprak
1       Akören        Kumlu toprak
2      Akşehir      Verimli toprak
3    Altınekin        Kumlu toprak
4     Beyşehir       Taşlık toprak
5       Bozkır      Verimli toprak
6       Çeltik        Tuzlu toprak
7   Cihanbeyli         Sulu toprak
8        Çumra  Kumlu-killi toprak
9      Derbent        Killi toprak
10   Derebucak        Kumlu toprak
11  Doğanhisar      Verimli toprak
12    Emirgazi       Taşlık toprak
13      Ereğli        Killi toprak
14  Güneysınır      Verimli toprak
15       Hadim        Kumlu toprak
16  Halkapınar       Taşlık toprak
17       Hüyük  Kumlu-killi toprak
18       Ilgın        Killi toprak
19   Kadınhanı      Verimli toprak
20   Karapınar        Tuzlu toprak
21     Karatay        Killi toprak
22        Kulu        Kumlu toprak
23       Meram      Verimli toprak
24    Sarayönü  Kumlu-killi toprak
25    Selçuklu        Killi toprak
26  Seydişehir        Kumlu toprak
27     Taşkent      Verimli toprak
28    Tuzlukçu       Taşlık toprak
29   Yalıhüyük        Killi toprak
30       Yunak        Kumlu toprak

In [122]:
merged_df = merged_df.merge(df_toprak_ilce,on='ilce_adi', how='outer')
merged_df[0:250:30]

,ilce_adi,mahalle_adi,tarimsal_sulama_suyu,sulama_suyu_kaynagi_yonetimi,en_cok_yetistirilen_urunler,sulanabilir_alanda_yetistirilen_urunler,talep_edilen_tarimsal_egitimler,sulak_alan_miktari,tarimsal_sulama_suyu_kaynagi,toprak_tipi
0,Ahırlı,ALİÇERÇİ,YOK,YOK,"BUĞDAY, ARPA, MERCİMEK, NOHUT, FASULYE",YOK,"HAYVANCILIK, MODERN BAĞCILIK, TARLA BİTKİLERİ ...",10%,YOK,Killi toprak
30,Akşehir,ÇAMLI,VAR,SULAMA BİRLİĞİ,"ELMA, KİRAZ, ÇİLEK, VİŞNE","MISIR, VİŞNE, ERİK","MODERN SULAMA SİSTEMLERİ, HAYVANCILIK, ÇİLEK Y...",60%,"ÇAY, KANAL",Verimli toprak
60,Altınekin,HACINUMAN,VAR,"ŞAHSİ KUYULAR, SULAMA KOOPERATİFİ","BUĞDAY, ARPA, AYÇİÇEĞİ, FASULYE","ŞEKER PANCARI, MISIR, AYÇİÇEĞİ, FASULYE","HAYVANCILIK, TARLA BİTKİLERİ YETİŞTİRİCİLİĞİ",40%,ŞAHSİ KUYULAR,Kumlu toprak
90,Beyşehir,EĞİRLER,VAR,ŞAHSİ KUYULAR,"BUĞDAY, ARPA","BUĞDAY, ARPA, YONCA",YOK,50%,"ŞAHSİ KUYULAR, YERALTI SULARI",Taşlık toprak
120,Beyşehir,YEŞİLDAĞ,VAR,"ŞAHSİ KUYULAR, SULAMA BİRLİĞİ","BUĞDAY, DOMATES, PATATES, ARPA","FASULYE, DOMATES, BİBER, PATLICAN, PATATES, SOĞAN",SEBZE YETİŞTİRİCİLİĞİ,45%,AKARSU,Taşlık toprak
150,Bozkır,KINIK,VAR,ŞAHSİ KUYULAR,"BUĞDAY, ARPA","ELMA, ÜZÜM","MODERN SULAMA SİSTEMLERİ, SEBZE YETİŞTİRİCİLİĞ...",10%,ŞAHSİ KUYULAR,Verimli toprak
180,Çeltik,İSHAKUŞAĞI,VAR,"ŞAHSİ KUYULAR, SULAMA KOOPERATİFİ","MISIR, BUĞDAY, ARPA, AYÇİÇEĞİ, REZENE","ŞEKER PANCARI, MISIR, AYÇİÇEĞİ, REZENE","MODERN SULAMA SİSTEMLERİ, KIRSALDAN KENTE GÜVE...",70%,YERALTI SULARI,Tuzlu toprak
210,Cihanbeyli,TAŞPINAR,VAR,ŞAHSİ KUYULAR,"MISIR, BUĞDAY, AYÇİÇEĞİ, ŞEKER PANCARI","ŞEKER PANCARI, MISIR, AYÇİÇEĞİ",HAYVANCILIK,70%,"ŞAHSİ KUYULAR, YERALTI SULARI",Sulu toprak
240,Çumra,DİNLENDİK,VAR,ŞAHSİ KUYULAR,"MISIR, BUĞDAY, ARPA, ŞEKER PANCARI","ŞEKER PANCARI, MISIR","MODERN SULAMA SİSTEMLERİ, HAYVANCILIK, TARLA B...",95%,YERALTI SULARI,Kumlu-killi toprak